###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        restart: unless-stopped

    redis:
        image: 'redis:alpine'
        restart: unless-stopped

    mariadb:
        image: 'mariadb:11.0'
        restart: unless-stopped
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=morning_workships
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        ports:
            - '57003:3306'

    webserver:
        image: 'nginx:alpine'
        restart: unless-stopped
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '57000:80'

    php-fpm:
        build: phpdocker/php-fpm
        restart: unless-stopped
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
